version: '3'
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3000"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    command: bash -c "npm install && npm run build --prod"
    volumes:
      - ./frontend:/code/frontend
