# Generated by Django 3.0.6 on 2020-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('duration', models.DurationField()),
                ('validity_duration', models.DurationField()),
                ('description', models.TextField()),
            ],
        ),
    ]
