# Generated by Django 3.0.6 on 2020-06-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpackage',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='validity_duration',
            field=models.CharField(max_length=255),
        ),
    ]
